function u3 = control_law_agent3(in1,in2)
%CONTROL_LAW_AGENT3
%    U3 = CONTROL_LAW_AGENT3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-Jun-2026 22:45:09

nu1 = in2(1,:);
nu2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x1);
t3 = cos(x3);
t4 = sin(x1);
t5 = sin(x3);
t6 = t2.^2;
t7 = t3.^2;
t8 = t4.^2;
t9 = t5.^2;
t10 = t4.*t5.*1.6e+1;
u3 = [(nu1.*-3.0e+3-x2.*9.0e+2-x2.*sin(x1.*2.0).*1.5e+1+nu2.*t4.*2.0e+2+nu1.*t6.*5.0e+2+t4.*x4.*7.0e+1+t6.*x2.*1.5e+2+t5.*x4.*4.5e+2-t5.*t6.*x4.*7.5e+1)./(t8.*-6.0e+2+t9.*5.0e+2+t10+t8.*t9.*1.0e+2-3.0e+3);-(nu2.*2.5e+3+x4.*9.05e+2-nu1.*t5.*2.0e+2+nu2.*t7.*5.0e+2-t2.*x2.*3.75e+2-t5.*x2.*6.0e+1+t7.*x4.*1.45e+2-t2.*t7.*x2.*7.5e+1)./(t6.*5.0e+2-t7.*6.0e+2+t10+t6.*t7.*1.0e+2-3.0e+3)];
end
