function u2 = control_law_agent2(in1,in2)
%CONTROL_LAW_AGENT2
%    U2 = CONTROL_LAW_AGENT2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-Jun-2026 22:45:09

nu1 = in2(1,:);
nu2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
u2 = [(sin(x1).^2./4.0+1.0).*(nu1+x2.*(2.0./5.0));(nu2+x4.*(1.1e+1./2.0e+1)).*(cos(x3).^2.*(3.0./1.0e+1)+1.0)];
end
