function u1 = control_law_agent1(in1,in2)
%CONTROL_LAW_AGENT1
%    U1 = CONTROL_LAW_AGENT1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    18-Jun-2026 22:45:08

nu1 = in2(1,:);
nu2 = in2(2,:);
x2 = in1(2,:);
x4 = in1(4,:);
u1 = [nu1.*(6.0./5.0)+x2.*(abs(x2).*8.0+3.5e+1).*(3.0./2.5e+2);nu2.*(6.0./5.0)+x4.*(abs(x4).*2.0+9.0).*(3.0./5.0e+1)];
end
